/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as AcabamentosRouteImport } from './routes/acabamentos'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const AcabamentosRoute = AcabamentosRouteImport.update({
  id: '/acabamentos',
  path: '/acabamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acabamentos': typeof AcabamentosRoute
  '/contato': typeof ContatoRoute
  '/obras': typeof ObrasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acabamentos': typeof AcabamentosRoute
  '/contato': typeof ContatoRoute
  '/obras': typeof ObrasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acabamentos': typeof AcabamentosRoute
  '/contato': typeof ContatoRoute
  '/obras': typeof ObrasRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/acabamentos' | '/contato' | '/obras' | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/acabamentos' | '/contato' | '/obras' | '/sobre'
  id: '__root__' | '/' | '/acabamentos' | '/contato' | '/obras' | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcabamentosRoute: typeof AcabamentosRoute
  ContatoRoute: typeof ContatoRoute
  ObrasRoute: typeof ObrasRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acabamentos': {
      id: '/acabamentos'
      path: '/acabamentos'
      fullPath: '/acabamentos'
      preLoaderRoute: typeof AcabamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcabamentosRoute: AcabamentosRoute,
  ContatoRoute: ContatoRoute,
  ObrasRoute: ObrasRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
